---
title: "Zillow Cleaning"
author: "Kai Addae and Taylor Holdaway"
date: "May 23, 2016"
output: html_document
---

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(ggmap)
library(reshape2)
library(broom)
library(stringr)

library(maptools)
library(rgeos)
library(sp)
library(plm)
library(pglm)
```

```{r zillow house value index data}
zhvi <- read.csv("data/Neighborhood_Zhvi_AllHomes.csv")
```


```{r zhvi cleaning}
zhvi <- zhvi %>% 
  #only house values in SF, CA metro area
  dplyr::filter(State == "CA", Metro == "San Francisco") %>%
  #get rid of sizerank variable
  dplyr::select(-SizeRank) %>%
  #reshape wide to long
  reshape2::melt(id.vars = c("RegionID","RegionName","City","State","Metro","CountyName"),variable.name = "year.mo", value.name = "valueIndex") %>%
  #get rid of "X" at start of year.mo
  dplyr::mutate(year.mo = gsub("X","",year.mo)) %>%
  #split year.month on ".", make first vector into year, second into month
  dplyr::mutate(year = as.numeric(stringr::str_split_fixed(year.mo,"[.]",n=2)[,1]), month = as.numeric(stringr::str_split_fixed(year.mo,"[.]",n=2)[,2]), year.mo = NULL)

names(zhvi) <- tolower(names(zhvi))
saveRDS(zhvi,"zhvi-df.rds")
```


```{r read shape file}
#path to shapefile
file <- "data/ZillowNeighborhoods-CA/ZillowNeighborhoods-CA.shp"
#create polygon from shapefile
nbhd.shape <- maptools::readShapePoly(file)
#get rid of neighborhoods outside of SF metro
nbhd.shape <- nbhd.shape[nbhd.shape@data$CITY == "San Francisco" | nbhd.shape@data$CITY == "Hayward" | nbhd.shape@data$CITY == "Fremont" | nbhd.shape@data$CITY == "Oakland" | nbhd.shape@data$CITY == "San Mateo" | nbhd.shape@data$CITY == "Menlo Park",]
#save
saveRDS(nbhd.shape,file="nbhd_shape.rds")
#tidy to a dataframe
nbhd.df <- broom::tidy(nbhd.shape, region = ("REGIONID")) %>%
  dplyr::mutate(REGIONID = as.numeric(id), id = NULL)
#make sure that the dataframe has region id and name
nbhd.df <- nbhd.shape@data %>%
  dplyr::select(NAME,REGIONID) %>%
  dplyr::right_join(nbhd.df)
  
names(nbhd.df) <- tolower(names(nbhd.df))
```


```{r get map}

#some map crap
#sf.map.12 <- ggmap::get_map("san francisco", zoom = 12)
#saveRDS(sf.map.12,"sf-map-12.rds")
sf.map.12 <- readRDS("sf-map-12.rds")
ggmap(sf.map.12) +
  geom_polygon(aes(x=long, y=lat, group=group), alpha = 0.25, data=nbhd.df, fill='white', color = "black")
```

```{r merge shape dataframe and zhvi data}
zhvi.nbhd.df <- dplyr::left_join(nbhd.df,zhvi) %>% dplyr::arrange(order)
saveRDS(zhvi.nbhd.df,file="zhvi_nbhd_df.rds")
```

```{r Plot of January 2014 Value Data}
ggmap(sf.map.12) + geom_polygon(aes(x=long,y=lat, group=group, fill = valueindex), alpha = 0.9, data=filter(zhvi.nbhd.df,year==2014, month==1,city == "San Francisco"), color = "black")
```

```{r Messing with fill for Jan 2014 plot, white to red}
ggmap(sf.map.12) +
  geom_polygon(aes(x=long,y=lat, group=group, fill = valueindex), alpha = 0.9, data=filter(zhvi.nbhd.df,year==2014, month==1,city == "San Francisco"), color = "black") +
  scale_fill_gradient("House Value Index", low = "White", high = "red")

```

```{r Fill- setting a rainbow gradient, Jan 2014}
ggmap(sf.map.12) +
  geom_polygon(aes(x=long,y=lat, group=group, fill = valueindex), alpha = 0.9, data=filter(zhvi.nbhd.df,year==2014, month==1,city == "San Francisco"), color = "black") +
  scale_fill_gradientn(colours = rainbow(7))

```

